window.LESSONS = [
    {
        lesson: 1.0,
        title: 'Основные слова',
        words: [
            { greek: "το βιβλίο", russian: "книга" },
            { greek: "το τετράδιο", russian: "тетрадь" },
            { greek: "το περιοδικό", russian: "журнал" },
            { greek: "το μολύβι", russian: "карандаш" },
            { greek: "το στυλό", russian: "ручка" },
            { greek: "η πένα", russian: "ручка" },
            { greek: "το σχολείο", russian: "школа" },
            { greek: "το δωμάτιο", russian: "комната" },
            { greek: "το σπίτι", russian: "дом" },
            { greek: "το γραφείο", russian: "офис, кабинет, письменный стол" },
            { greek: "το τηλέφωνο", russian: "телефон" },
            { greek: "το ραδιόφωνο", russian: "радио" },
            { greek: "το ρολόι", russian: "часы" },
            { greek: "το αυτοκίνητο", russian: "машина" },
            { greek: "το παράθυρο", russian: "окно" },
            { greek: "η πόρτα", russian: "дверь" },
            { greek: "ο τοίχος", russian: "стена" },
            { greek: "το πάρκο", russian: "парк" },
            { greek: "το κουτί", russian: "коробка" },
            { greek: "το βάζο", russian: "ваза" },
            { greek: "το κομπιούτερ", russian: "компьютер" },
            { greek: "το ερμάρι", russian: "шкаф" },
            { greek: "το τραπέζι", russian: "стол" },
            { greek: "το πάτωμα", russian: "пол" },
            { greek: "το ταβάνι", russian: "потолок" },
            { greek: "το κλειδί", russian: "ключ" },
            { greek: "το διαμέρισμα", russian: "квартира" },
            { greek: "το λουλούδι", russian: "цветок" },
            { greek: "το καλάθι", russian: "корзина" },
            { greek: "το γράμμα", russian: "письмо" },
            { greek: "το κατάστημα", russian: "магазин" },
            { greek: "το πράγμα", russian: "вещь" },
            { greek: "το φόρεμα", russian: "платье" },
            { greek: "το μάθημα", russian: "урок" },
            { greek: "το μήλο", russian: "яблоко" },
            { greek: "το φρούτο", russian: "фрукт" },
            { greek: "το νερό", russian: "вода" },
            { greek: "το ψωμί", russian: "хлеб" },
            { greek: "ο μαθητής", russian: "ученик" },
            { greek: "η μαθήτρια", russian: "ученица" },
            { greek: "ο δάσκαλος", russian: "учитель" },
            { greek: "η δασκάλα", russian: "учительница" },
            { greek: "ο γιατρός", russian: "врач" },
            { greek: "ο κύριος", russian: "господин" },
            { greek: "η κυρία", russian: "госпожа" },
            { greek: "ο φοιτητής", russian: "студент" },
            { greek: "η φοιτήτρια", russian: "студентка" },
            { greek: "η καρέκλα", russian: "стул" },
            { greek: "το παιδί", russian: "ребёнок, дети" },
            { greek: "το ποδήλατο", russian: "велосипед" },
            { greek: "το πουκάμισο", russian: "рубашка" },
            { greek: "το παλτό", russian: "пальто" },
            { greek: "το σακάκι", russian: "куртка, пиджак" },
            { greek: "το καπέλο", russian: "шапка" },
            { greek: "το παντελόνι", russian: "брюки" },
            { greek: "ο πίνακας", russian: "доска, картина" },
            { greek: "ο χαρτοφύλακας", russian: "портфель" },
            { greek: "η τσάντα", russian: "сумка" },
            { greek: "η πόλη", russian: "город" },
            { greek: "το χωριό", russian: "деревня" },
            { greek: "το όνομα", russian: "имя" },
            { greek: "ο άντρας", russian: "мужчина, муж" },
            { greek: "η γυναίκα", russian: "женщина, жена" },
            { greek: "ο καθηγητής", russian: "преподаватель" },
            { greek: "η καθηγήτρια", russian: "преподавательница" },
            { greek: "η τάξη", russian: "класс" },
            { greek: "η χώρα", russian: "страна" }
        ]
    }
];

// Lesson 2: countries
window.LESSONS.push({
    lesson: 1.1,
    title: 'Страны',
    words: [
        { greek: 'η Ρωσία', russian: 'Россия' },
        { greek: 'η Ελλάδα', russian: 'Греция' },
        { greek: 'η Τουρκία', russian: 'Турция' },
        { greek: 'η Αγγλία', russian: 'Англия' },
        { greek: 'η Ισπανία', russian: 'Испания' },
        { greek: 'ο Καναδάς', russian: 'Канада' },
        { greek: 'ο Λίβανος', russian: 'Ливан' },
        { greek: 'η Βουλγαρία', russian: 'Болгария' },
        { greek: 'το Βέλγιο', russian: 'Бельгия' },
        { greek: 'η Γαλλία', russian: 'Франция' },
        { greek: 'η Γερμανία', russian: 'Германия' },
        { greek: 'η Κύπρος', russian: 'Кипр' },
        { greek: 'η Ιταλία', russian: 'Италия' },
        { greek: 'η Λευκορωσία', russian: 'Белоруссия' },
        { greek: 'η Ουκρανία', russian: 'Украина' }
    ]
});

// User-provided lesson (marked as "Урок 2" in user's list)
window.LESSONS.push({
    lesson: 2.0,
    title: 'Основные слова',
    words: [
        { greek: 'το επώνυμο', russian: 'фамилия' },
        { greek: 'το επίθετο', russian: 'фамилия' },
        { greek: 'η διεύθυνση', russian: 'адрес' },
        { greek: 'η περιοχή', russian: 'район' },
        { greek: 'ο ταχυδρομικός κώδικας', russian: 'почтовый индекс' },
        { greek: 'το σταθερό', russian: 'домашний телефон' },
        { greek: 'το κινητό', russian: 'мобильный' },
        { greek: 'ακριβώς', russian: 'именно, точно, ровно' },
        { greek: 'το νούμερο', russian: 'номер' },
        { greek: 'ο δρόμος', russian: 'дорога, улица, путь' },
        { greek: 'η θάλασσα', russian: 'море' },
        { greek: 'το φαρμακείο', russian: 'аптека' },
        { greek: 'ο ήλιος', russian: 'солнце' },
        { greek: 'ο ουρανός', russian: 'небо' },
        { greek: 'το μουσείο', russian: 'музей' },
        { greek: 'το εστιατόριο', russian: 'ресторан' },
        { greek: 'το περίπτερο', russian: 'киоск' },
        { greek: 'η ταβέρνα', russian: 'таверна' },
        { greek: 'το νοσοκομείο', russian: 'больница' },
        { greek: 'ο φούρνος', russian: 'хлебный магазин' },
        { greek: 'το μαγαζί', russian: 'магазин, заведение' },
        { greek: 'το θέατρο', russian: 'театр' },
        { greek: 'το ξενοδοχείο', russian: 'гостиница' },
        { greek: 'το πρόβλημα', russian: 'проблема' },
        { greek: 'το δημαρχείο', russian: 'мэрия' },
        { greek: 'το εργοστάσιο', russian: 'завод' },
        { greek: 'το ταχυδρομείο', russian: 'почта' },
        { greek: 'το βιβλιοπωλείο', russian: 'книжный магазин' },
        { greek: 'το αεροδρόμιο', russian: 'аэропорт' },
        { greek: 'το κρέας', russian: 'мясо' },
        { greek: 'το κρασί', russian: 'вино' },
        { greek: 'το γάλα', russian: 'молоко' },
        { greek: 'το ποτήρι', russian: 'стакан' },
        { greek: 'το μπουκάλι', russian: 'бутылка' },
        { greek: 'τα λεφτά', russian: 'деньги' },
        { greek: 'τα χρήματα', russian: 'деньги' },
        { greek: 'η θέρμανση', russian: 'отопление' },
        { greek: 'η εφημερίδα', russian: 'газета' },
        { greek: 'το ποδόσφαιρο', russian: 'футбол' },
        { greek: 'το ψάρι', russian: 'рыба' },
        { greek: 'η έκθεση', russian: 'выставка, сочинение' },
        { greek: 'το βράδυ', russian: 'вечер, вечером' },
        { greek: 'το παγωτό', russian: 'мороженое' },
        { greek: 'το πιάνο', russian: 'пианино' },
        { greek: 'ο χυμός', russian: 'сок' },
        { greek: 'ο καφές', russian: 'кофе' },
        { greek: 'το λιμάνι', russian: 'порт' },
        { greek: 'η στάση', russian: 'остановка' },
        { greek: 'η τράπεζα', russian: 'банк' },
        { greek: 'η πλατεία', russian: 'площадь' },
        { greek: 'ο κινηματογράφος', russian: 'кинотеатр, кинематограф' },
        { greek: 'το τρένο', russian: 'поезд' },
        { greek: 'το μετρό', russian: 'метро' },
        { greek: 'το λεωφορείο', russian: 'автобус' },
        { greek: 'ήδη / πια', russian: 'уже' },
        { greek: 'καλά', russian: 'хорошо' },
        { greek: 'το σκυλάκι', russian: 'собачка' },
        { greek: 'τώρα', russian: 'сейчас' },
        { greek: 'κοντά', russian: 'недалеко' },
        { greek: 'εδώ', russian: 'здесь' },
        { greek: 'εκεί', russian: 'там' },
        { greek: 'συχνά', russian: 'часто' },
        { greek: 'συνήθως', russian: 'обычно' },
        { greek: 'πάντα', russian: 'всегда' },
        { greek: 'σπάνια', russian: 'редко' },
        { greek: 'ποτέ', russian: 'никогда' },
        { greek: 'τα Ελληνικά', russian: 'греческий язык' },
        { greek: 'τα Ρωσικά', russian: 'русский язык' },
        { greek: 'τα Αγγλικά', russian: 'английский язык' },
        { greek: 'το πορτοφόλι', russian: 'кошелёк' },
        { greek: 'το παραμύθι', russian: 'сказка' }
    ]
});

// Lesson: Глаголы
window.LESSONS.push({
    lesson: 2.1,
    title: 'Глаголы',
    words: [
        { greek: 'μένω', russian: 'жить' },
        { greek: 'έχω', russian: 'иметь' },
        { greek: 'κάνω', russian: 'делать' },
        { greek: 'διαβάζω', russian: 'читать' },
        { greek: 'γράφω', russian: 'писать' },
        { greek: 'παίζω', russian: 'играть' },
        { greek: 'μαθαίνω', russian: 'учить' },
        { greek: 'μαγειρεύω', russian: 'готовить еду' },
        { greek: 'ξέρω', russian: 'знать' },
        { greek: 'βλέπω', russian: 'видеть' },
        { greek: 'κοιτάζω', russian: 'смотреть' },
        { greek: 'θέλω', russian: 'хотеть' },
        { greek: 'αγοράζω', russian: 'покупать' },
        { greek: 'δουλεύω', russian: 'работать' },
        { greek: 'καπνίζω', russian: 'курить' },
        { greek: 'καταλαβαίνω', russian: 'понимать' },
        { greek: 'σπουδάζω', russian: 'учиться (в ВУЗЕ)' },
        { greek: 'διδάσκω', russian: 'преподавать' },
        { greek: 'πηγαίνω', russian: 'идти, ходить, ехать, ездить' },
        { greek: 'περιμένω', russian: 'ждать' }
    ]
});

// Lesson 3: family & jobs
window.LESSONS.push({
    lesson: 3.0,
    title: 'Урок 3',
    words: [
        { greek: 'η οικογένεια', russian: 'семья' },
        { greek: 'η μητέρα', russian: 'мама' },
        { greek: 'η μαμά', russian: 'мама' },
        { greek: 'ο πατέρας', russian: 'папа' },
        { greek: 'ο μπαμπάς', russian: 'папа' },
        { greek: 'η κόρη', russian: 'дочь' },
        { greek: 'ο γιος', russian: 'сын' },
        { greek: 'ο αδελφός', russian: 'брат' },
        { greek: 'ο αδερφός', russian: 'брат' },
        { greek: 'η αδελφή', russian: 'сестра' },
        { greek: 'η αδερφή', russian: 'сестра' },
        { greek: 'τα αδέλφια', russian: 'братья и сёстры' },
        { greek: 'τα αδέρφια', russian: 'братья и сёстры' },
        { greek: 'ο παππούς', russian: 'дедушка' },
        { greek: 'η γιαγιά', russian: 'бабушка' },
        { greek: 'ο εγγονός', russian: 'внук' },
        { greek: 'η εγγονή', russian: 'внучка' },
        { greek: 'τα εγγόνια', russian: 'внуки' },
        { greek: 'ο θείος', russian: 'дядя' },
        { greek: 'η θεία', russian: 'тётя' },
        { greek: 'ο ξάδελφος', russian: 'двоюродный брат' },
        { greek: 'ο ξαδερφος', russian: 'двоюродный брат' },
        { greek: 'η ξαδέλφη', russian: 'двоюродная сестра' },
        { greek: 'η ξαδερφη', russian: 'двоюродная сестра' },
        { greek: 'τα ξαδέλφια', russian: 'двоюродные братья и сёстры' },
        { greek: 'τα ξαδέρφια', russian: 'двоюродные братья и сёстры' },
        { greek: 'ο ανιψιός', russian: 'племянник' },
        { greek: 'η ανιψιά', russian: 'племянница' },
        { greek: 'τα ανίψια', russian: 'племянники' },
        { greek: 'οι γονείς', russian: 'родители' },
        { greek: 'το σόι', russian: 'родня' },
        { greek: 'οι συγγενείς', russian: 'родственники' },
        { greek: 'το αγόρι', russian: 'мальчик' },
        { greek: 'το κορίτσι', russian: 'девочка' },
        { greek: 'η οικογενειακή κατάσταση', russian: 'семейное положение' },
        { greek: 'παντρεμένος', russian: 'женатый' },
        { greek: 'παντρεμένη', russian: 'замужняя' },
        { greek: 'ανύπαντρος', russian: 'неженатый' },
        { greek: 'ανύπαντρη', russian: 'незамужняя' },
        { greek: 'ελεύθερος', russian: 'свободный' },
        { greek: 'ελεύθερη', russian: 'свободная' },
        { greek: 'αρραβωνιασμένος', russian: 'обручённый' },
        { greek: 'αρραβωνιασμένη', russian: 'обручённая' },
        { greek: 'χωρισμένος', russian: 'разведённый' },
        { greek: 'χωρισμένη', russian: 'разведённая' },
        { greek: 'ο χήρος', russian: 'вдовец' },
        { greek: 'η χήρα', russian: 'вдова' },
        { greek: 'η δουλειά', russian: 'работа' },
        { greek: 'ο δικηγόρος', russian: 'адвокат' },
        { greek: 'η δικηγόρος', russian: 'адвокат' },
        { greek: 'ο ηλεκτρολόγος', russian: 'электрик' },
        { greek: 'η ηλεκτρολόγος', russian: 'электрик' },
        { greek: 'ο οδηγός', russian: 'водитель' },
        { greek: 'η οδηγός', russian: 'водитель' },
        { greek: 'ο μηχανικός', russian: 'инженер' },
        { greek: 'η μηχανικός', russian: 'инженер' },
        { greek: 'ο υπάλληλος', russian: 'служащий' },
        { greek: 'η υπάλληλος', russian: 'служащая' },
        { greek: 'ο ηθοποιός', russian: 'актёр' },
        { greek: 'η ηθοποιός', russian: 'актриса' },
        { greek: 'ο ταμίας', russian: 'кассир' },
        { greek: 'η ταμίας', russian: 'кассир' },
        { greek: 'ο αρχιτέκτονας', russian: 'архитектор' },
        { greek: 'η αρχιτέκτονας', russian: 'архитектор' },
        { greek: 'ο γραμματέας', russian: 'секретарь' },
        { greek: 'η γραμματέας', russian: 'секретарь' },
        { greek: 'ο δημοσιογράφος', russian: 'журналист' },
        { greek: 'η δημοσιογράφος', russian: 'журналистка' },
        { greek: 'ο φαρμακοποιός', russian: 'фармацевт' },
        { greek: 'η φαρμακοποιός', russian: 'фармацевт' },
        { greek: 'ο αρχαιολόγος', russian: 'археолог' },
        { greek: 'η αρχαιολόγος', russian: 'археолог' },
        { greek: 'ο φωτογράφος', russian: 'фотограф' },
        { greek: 'η φωτογράφος', russian: 'фотограф' },
        { greek: 'ο οδοντίατρος', russian: 'зубной врач' },
        { greek: 'η οδοντίατρος', russian: 'зубной врач' },
        { greek: 'ο μαθηματικός', russian: 'математик' },
        { greek: 'η μαθηματικός', russian: 'математик' },
        { greek: 'ο κομμωτής', russian: 'парикмахер' },
        { greek: 'η κομμώτρια', russian: 'парикмахерша' },
        { greek: 'ο εργάτης', russian: 'рабочий' },
        { greek: 'η εργάτρια', russian: 'рабочая' },
        { greek: 'ο πωλητής', russian: 'продавец' },
        { greek: 'η πωλήτρια', russian: 'продавщица' },
        { greek: 'ο αθλητής', russian: 'спортсмен' },
        { greek: 'η αθλήτρια', russian: 'спортсменка' },
        { greek: 'ο σερβιτόρος', russian: 'официант' },
        { greek: 'η σερβιτόρα', russian: 'официантка' },
        { greek: 'ο νοσοκόμος', russian: 'медбрат' },
        { greek: 'η νοσοκόμα', russian: 'медсестра' },
        { greek: 'ο άνεργος', russian: 'безработный' },
        { greek: 'η άνεργη', russian: 'безработная' },
        { greek: 'ο μάγειρας', russian: 'повар' },
        { greek: 'η μαγείρισσα', russian: 'повар' },
        { greek: 'ο τραγουδιστής', russian: 'певец' },
        { greek: 'η τραγουδίστρια', russian: 'певица' },
        { greek: 'ο φίλος', russian: 'друг' },
        { greek: 'η φίλη', russian: 'подруга' },
        { greek: 'μαζί', russian: 'вместе' },
        { greek: 'ταξιδεύω', russian: 'путешествовать' },
        { greek: 'το σούπερ μάρκετ', russian: 'супермаркет' },
        { greek: 'το κομμωτήριο', russian: 'парикмахерская' },
        { greek: 'το συνεργείο', russian: 'ремонтная мастерская, бригада' },
        { greek: 'ψάχνω (για)', russian: 'искать' },
        { greek: 'το ταμείο', russian: 'касса' },
        { greek: 'η ιστορία', russian: 'история' },
        { greek: 'το δικηγορικό γραφείο', russian: 'адвокатская контора' },
        { greek: 'το φωτογραφείο', russian: 'фотоателье' },
        { greek: 'η φωτογραφία', russian: 'фотография' }
    ]
});

window.LESSONS.push({
    lesson: 4.1,
    title: 'Существительные и прилагательные',
    words: [
        { greek: 'το καφενείο / η καφετέρια', russian: 'кафе' },
        { greek: 'ο σταθμός', russian: 'станция, вокзал' },
        { greek: 'η αγγελία', russian: 'объявление' },
        { greek: 'η αμοιβή', russian: 'оплата услуг, гонорар' },
        { greek: 'ο χώρος', russian: 'место, пространство, территория, помещение' },
        { greek: 'η γραμματεία', russian: 'секретариат, приемная' },
        { greek: 'το ωράριο', russian: 'график работы, часы работы' },
        { greek: 'η ρεσεψιόν', russian: 'администрация, приемная' },
        { greek: 'η ώρα', russian: 'время, час' },
        { greek: 'η γνώση', russian: 'знание' },
        { greek: 'η εταιρεία', russian: 'компания, фирма' },
        { greek: 'το έντυπο', russian: 'бланк' },
        { greek: 'η εγγραφή', russian: 'запись, регистрация' },
        { greek: 'η εθνικότητα', russian: 'национальность' },
        { greek: 'η γλώσσα', russian: 'язык' },
        { greek: 'το επάγγελμα', russian: 'профессия' },
        { greek: 'η αρχαιολογία', russian: 'археология' },
        { greek: 'το πανεπιστήμιο', russian: 'университет' },
        { greek: 'η κάρτα / ο χάρτης', russian: 'карта' },
        { greek: 'το θρανίο', russian: 'парта' },
        { greek: 'το σφουγγάρι', russian: 'губка' },
        { greek: 'το ράφι', russian: 'полка' },
        { greek: 'η βιβλιοθήκη', russian: 'библиотека' },
        { greek: 'ο υπολογιστής', russian: 'компьютер' },
        { greek: 'το σπουδαστήριο', russian: 'зал для занятий в учебном заведении' },
        { greek: 'ο μαρκαδόρος', russian: 'маркер' },
        { greek: 'το σακίδιο', russian: 'рюкзак' },
        { greek: 'το διάλειμμα', russian: 'перемена, перерыв' },
        { greek: 'το δίπλωμα / το πτυχίο', russian: 'диплом' },
        { greek: 'το πρόγραμμα', russian: 'программа' },
        { greek: 'το αμφιθέατρο', russian: 'амфитеатр' },
        { greek: 'το κυλικείο', russian: 'буфет' },
        { greek: 'το μέρος', russian: 'место, часть' },
        { greek: 'ο μάγος', russian: 'маг' },
        { greek: 'τα νομικά', russian: 'правоведение, юриспруденция' },
        { greek: 'τα οικονομικά', russian: 'экономика' },
        { greek: 'η ψυχολογία', russian: 'психология' },
        { greek: 'η ιατρική', russian: 'медицина' },
        { greek: 'η φιλολογία', russian: 'филология' },
        { greek: 'η πληροφορική', russian: 'информатика' },
        { greek: 'η αρχιτεκτονική', russian: 'архитектура' },
        { greek: 'τα παιδαγωγικά', russian: 'педагогика' },
        { greek: 'η μετάφραση / η διερμηνεία', russian: 'перевод' },
        { greek: 'η σχολή', russian: 'факультет, школа' },
        { greek: 'το τμήμα', russian: 'отделение, отдел' },
        { greek: 'η αίθουσα', russian: 'зал' },
        { greek: 'το πάσο', russian: 'пропуск, проездной' },
        { greek: 'το εισιτήριο', russian: 'билет' },
        { greek: 'το μεταπτυχιακό', russian: 'магистратура' },
        { greek: 'το διδακτορικό', russian: 'докторантура' },
        { greek: 'η εργασία', russian: 'работа, труд, письменная работа' },
        { greek: 'η μπίρα', russian: 'пиво' },
        { greek: 'το σουβλάκι', russian: 'шашлык' },
        { greek: 'το κεφάλι', russian: 'голова' },
        { greek: 'το καλοκαίρι', russian: 'лето, летом' },
        { greek: 'η μπλούζα', russian: 'блузка' },
        { greek: 'η αίτηση', russian: 'заявление, прошение' },
        { greek: 'η συμμετοχή', russian: 'участие' },
        { greek: 'οι σπουδές', russian: 'учёба' },
        { greek: 'οι προσωπικές πληροφορίες', russian: 'личная информация' },
        { greek: 'τα κεφαλαία γράμματα', russian: 'заглавные буквы' },
        { greek: 'το φύλο', russian: 'пол' },
        { greek: 'η ημερομηνία γέννησης', russian: 'дата рождения' },
        { greek: 'το διαβατήριο (ο αριθμός διαβατηρίου)', russian: 'паспорт (номер паспорта)' },
        { greek: 'η ταυτότητα (ο αριθμός ταυτότητας)', russian: 'удостоверение личности' },
        { greek: 'ο / η κτηνίατρος', russian: 'ветеринар' },
        { greek: 'ο γυμναστής / η γυμνάστρια', russian: 'инструктор в спортзале, учитель физкультуры' },
        { greek: 'ο ξυλουργός', russian: 'плотник' },
        { greek: 'ιδιωτικός', russian: 'частный' },
        { greek: 'ξένος', russian: 'иностранный' },
        { greek: 'φιλικός', russian: 'дружелюбный' },
        { greek: 'καλός', russian: 'хороший' },
        { greek: 'πλήρης', russian: 'полный' },
        { greek: 'πρωινός', russian: 'утренний' },
        { greek: 'λίγο', russian: 'немного' },
        { greek: 'καθόλου', russian: 'совсем (не)' },
        { greek: 'αρκετά', russian: 'достаточно' }
    ]
});

window.LESSONS.push({
    lesson: 4.1,
    title: 'Глаголы',
    words: [
        { greek: 'αγαπώ / αγαπάω', russian: 'любить' },
        { greek: 'μιλώ / μιλάω', russian: 'говорить' },
        { greek: 'ζητώ / ζητάω', russian: 'просить, требовать, искать (человека)' },
        { greek: 'βοηθώ / βοηθάω', russian: 'помогать' },
        { greek: 'μελετώ / μελετάω', russian: 'изучать' },
        { greek: 'διψώ / διψάω', russian: 'хотеть пить' },
        { greek: 'πεινώ / πεινάω', russian: 'хотеть есть' },
        { greek: 'τραγουδώ / τραγουδάω', russian: 'петь' },
        { greek: 'πονώ / πονάω', russian: 'чувствовать боль' },
        { greek: 'ρωτώ / ρωτάω', russian: 'спрашивать' },
        { greek: 'απαντώ / απαντάω', russian: 'отвечать' },
        { greek: 'σταματώ / σταματάω', russian: 'останавливаться' },
        { greek: 'φορώ / φοράω', russian: 'носить' },
        { greek: 'φωνάζω', russian: 'кричать, звать' }
    ]
});

window.LESSONS.push({
    lesson: 5.1,
    title: 'Прилагательные',
    words: [
        { greek: 'μεγάλος', russian: 'большой' },
        { greek: 'μικρός', russian: 'маленький' },
        { greek: 'όμορφος', russian: 'красивый' },
        { greek: 'άσχημος', russian: 'некрасивый, плохой' },
        { greek: 'ακριβός', russian: 'дорогой' },
        { greek: 'φτηνός', russian: 'дешёвый' },
        { greek: 'καθαρός', russian: 'чистый' },
        { greek: 'καλός', russian: 'хороший' },
        { greek: 'ζεστός', russian: 'горячий' },
        { greek: 'έξυπνος', russian: 'умный' },
        { greek: 'εύκολος', russian: 'лёгкий' },
        { greek: 'δύσκολος', russian: 'трудный' },
        { greek: 'γεμάτος', russian: 'полный' },
        { greek: 'έτοιμος', russian: 'готовый' },
        { greek: 'ανοικτός', russian: 'открытый' },
        { greek: 'κλειστός', russian: 'закрытый' },
        { greek: 'γρήγορος', russian: 'быстрый' },
        { greek: 'ευγενικός', russian: 'вежливый' },
        { greek: 'δυνατός', russian: 'сильный, крепкий, реальный, громкий' },
        { greek: 'βρώμικος', russian: 'грязный' },
        { greek: 'αυστηρός', russian: 'строгий' },
        { greek: 'ψηλός', russian: 'высокий' },
        { greek: 'χαμηλός', russian: 'низкий (о предметах)' },
        { greek: 'κοντός', russian: 'низкий (о людях)' },
        { greek: 'νέος', russian: 'новый, молодой' },
        { greek: 'ωραίος', russian: 'прекрасный' },
        { greek: 'παλιός', russian: 'старый' },
        { greek: 'καινούργιος', russian: 'новый' },
        { greek: 'κρύος', russian: 'холодный' },
        { greek: 'άδειος', russian: 'пустой' },
        { greek: 'μοντέρνος', russian: 'современный' },
        { greek: 'σκούρος', russian: 'тёмный' },
        { greek: 'γκρίζος', russian: 'серый' }
    ]
});

window.LESSONS.push({
    lesson: 5.2,
    title: 'Существительные, Наречия, Вопросы',
    words: [
        { greek: 'το τουριστικό γραφείο', russian: 'туристическая фирма' },
        { greek: 'η οδός (στην οδό)', russian: 'улица (на улице)' },
        { greek: 'το κέντρο', russian: 'центр' },
        { greek: 'η μέρα', russian: 'день' },
        { greek: 'ο πολιτικός', russian: 'политик' },
        { greek: 'ο κόσμος', russian: 'мир, люди' },
        { greek: 'το εκατομμύριο', russian: 'миллион' },
        { greek: 'ο ποδοσφαιριστής', russian: 'футболист' },
        { greek: 'η λέξη', russian: 'слово' },
        { greek: 'το ποτό', russian: 'напиток' },
        { greek: 'η βοήθεια', russian: 'помощь' },
        { greek: 'το φαγητό', russian: 'еда' },
        { greek: 'το ταξί', russian: 'такси' },
        { greek: 'ο ταξιτζής', russian: 'таксист' },
        { greek: 'ο άνθρωπος', russian: 'человек' },
        { greek: 'η σχέση (έχω σχέση)', russian: 'связь, отношения' },
        { greek: 'ο δεσμός (έχω δεσμό)', russian: 'узел, связь, отношения' },
        { greek: 'η κοπέλα', russian: 'девушка' },
        { greek: 'το μοναχοπαίδι', russian: 'единственный ребёнок в семье' },
        { greek: 'το κουδούνι', russian: 'звонок' },
        { greek: 'ο συμφοιτητής / η συμφοιτήτρια', russian: 'однокурсник / однокурсница' },
        { greek: 'ο κήπος', russian: 'сад' },
        { greek: 'η ζακέτα', russian: 'жакет' },
        { greek: 'η άσκηση', russian: 'упражнение' },
        { greek: 'η έγκυος', russian: 'женщина в положении' },
        { greek: 'το σαλόνι', russian: 'зал' },
        { greek: 'η ταινία', russian: 'фильм' },
        { greek: 'το ρεπορτάζ', russian: 'репортаж' },
        { greek: 'η ηλικία', russian: 'возраст' },
        { greek: 'ο τόπος', russian: 'место' },
        { greek: 'η κατοικία', russian: 'дом' },
        { greek: 'η απάντηση', russian: 'ответ' },
        { greek: 'η μουσική', russian: 'музыка' },
        { greek: 'η Φιλοσοφική σχολή', russian: 'философский факультет' },
        { greek: 'ο / η ψυχολόγος', russian: 'психолог' },
        { greek: 'ο / η φιλόλογος', russian: 'филолог' },
        { greek: 'το τσάι', russian: 'чай' },
        { greek: 'μήπως', russian: 'может быть (вопрос)' },
        { greek: 'ίσως', russian: 'может быть (утверждение)' },
        { greek: 'μια μέρα', russian: 'однажды, когда-нибудь, как-нибудь' },
        { greek: 'πόσα', russian: 'сколько' },
        { greek: 'ακόμα', russian: 'ещё' },
        { greek: 'σωστά', russian: 'правильно' },
        { greek: 'σε λίγο', russian: 'скоро' }
    ]
});

window.LESSONS.push({
    lesson: 5.3,
    title: 'Глаголы',
    words: [
        { greek: 'συμπληρώνω', russian: 'заполнять' },
        { greek: 'πάω', russian: 'идти' },
        { greek: 'τρώω', russian: 'кушать' },
        { greek: 'πίνω', russian: 'пить' },
        { greek: 'φτιάχνω', russian: 'делать (что-то вещественное)' },
        { greek: 'σερβίρω', russian: 'сервировать' },
        { greek: 'ανοίγω', russian: 'открывать' },
        { greek: 'κλείνω', russian: 'закрывать' },
        { greek: 'αρχίζω', russian: 'начинать' },
        { greek: 'τελειώνω', russian: 'заканчивать' },
        { greek: 'φωτογραφίζω', russian: 'фотографировать' },
        { greek: 'κουρεύω', russian: 'стричь' },
        { greek: 'λέω', russian: 'говорить, сказать' },
        { greek: 'φταίω', russian: 'быть виноватым' },
        { greek: 'καίω', russian: 'жечь, сжигать' },
        { greek: 'κλαίω', russian: 'плакать' },
        { greek: 'ακούω', russian: 'слушать' }
    ]
});

window.LESSONS.push({
    lesson: 6.1,
    title: 'Существительные',
    words: [
        { greek: 'τα μέσα μαζικής μεταφοράς', russian: 'общественный транспорт' },
        { greek: 'το τρόλεϊ', russian: 'троллейбус' },
        { greek: 'το τραμ', russian: 'трамвай' },
        { greek: 'η μηχανή (το μηχανάκι)', russian: 'мотоцикл' },
        { greek: 'ο ηλεκτρικός (σιδηρόδρομος)', russian: 'метро' },
        { greek: 'ο προαστιακός', russian: 'пригородный поезд' },
        { greek: 'το αεροπλάνο', russian: 'самолёт' },
        { greek: 'το πλοίο', russian: 'теплоход, корабль' },
        { greek: 'το πόδι (τα πόδια)', russian: 'нога (ноги)' },
        { greek: 'η διαδρομή', russian: 'маршрут, дорога (выбранная)' },
        { greek: 'το βαγόνι', russian: 'вагон' },
        { greek: 'η πλατφόρμα', russian: 'платформа, перрон' },
        { greek: 'ο επιβάτης', russian: 'пассажир' },
        { greek: 'η λαϊκή', russian: 'рынок' },
        { greek: 'η γραμμή', russian: 'линия' },
        { greek: 'το ταξιδιωτικό γραφείο', russian: 'туристическая фирма' },
        { greek: 'η επιστροφή', russian: 'возврат, возвращение' },
        { greek: 'ο σκύλος', russian: 'собака' },
        { greek: 'η βόλτα', russian: 'прогулка' },
        { greek: 'το στέκι', russian: 'любимое место' },
        { greek: 'το πράσινο', russian: 'зелень (парки)' },
        { greek: 'ο πελάτης', russian: 'клиент' },
        { greek: 'η ιδέα', russian: 'идея' },
        { greek: 'η παραλία', russian: 'пляж, набережная' },
        { greek: 'το λούνα παρκ', russian: 'лунапарк' },
        { greek: 'η βαλίτσα', russian: 'чемодан' },
        { greek: 'η γειτονιά', russian: 'округа, соседство' },
        { greek: 'ο γείτονας / η γειτόνισσα', russian: 'сосед, соседка' },
        { greek: 'το δώρο', russian: 'подарок' },
        { greek: 'η αστυνομία', russian: 'полиция' },
        { greek: 'ο αστυνομικός', russian: 'полицейский' },
        { greek: 'ο φάκελος', russian: 'конверт' },
        { greek: 'το φως', russian: 'свет (светофор)' },
        { greek: 'τα νέα', russian: 'новости' },
        { greek: 'η τηλεόραση', russian: 'телевизор' },
        { greek: 'ο διευθυντής', russian: 'директор' },
        { greek: 'το ραντεβού', russian: 'приём' },
        { greek: 'το ταξίδι', russian: 'поездка' },
        { greek: 'το τηλεφώνημα', russian: 'телефонный звонок' },
        { greek: 'το τέλος', russian: 'конец' },
        { greek: 'το νησί', russian: 'остров' },
        { greek: 'η θέση', russian: 'место' },
        { greek: 'το ταξίδι', russian: 'путешествие, поездка' },
        { greek: 'το φάρμακο', russian: 'лекарство' }
    ]
});


window.LESSONS.push({
    lesson: 6.2,
    title: 'Глаголы',
    words: [
        { greek: 'συμφωνώ', russian: 'соглашаться' },
        { greek: 'χρησιμοποιώ', russian: 'использовать' },
        { greek: 'πληροφορώ', russian: 'информировать' },
        { greek: 'διαρκώ', russian: 'длиться' },
        { greek: 'κυκλοφορώ', russian: 'циркулировать, передвигаться' },
        { greek: 'ενοχλώ', russian: 'мешать, беспокоить' },
        { greek: 'ακολουθώ', russian: 'следовать' },
        { greek: 'μισώ', russian: 'ненавидеть' },
        { greek: 'λειτουργώ', russian: 'действовать, функционировать' },
        { greek: 'ξεκινώ / ξεκινάω', russian: 'начинать, выезжать' },
        { greek: 'περνώ / περνάω', russian: 'проводить, проходить' },
        { greek: 'βάζω', russian: 'класть, ставить' },
        { greek: 'δείχνω', russian: 'показывать' },
        { greek: 'φέρνω', russian: 'приносить' },
        { greek: 'βγάζω', russian: 'доставать, снимать' },
        { greek: 'συγχωρώ', russian: 'прощать' },
        { greek: 'αργώ', russian: 'опаздывать' },
        { greek: 'φεύγω', russian: 'уходить, уезжать' },
        { greek: 'φτάνω', russian: 'прибывать, успевать' },
        { greek: 'λέω', russian: 'говорить' },
        { greek: 'παίρνω', russian: 'брать, получать' },
        { greek: 'αποφασίζω', russian: 'решать' },
        { greek: 'μπαίνω', russian: 'входить' },
        { greek: 'βγαίνω', russian: 'выходить' },
        { greek: 'λατρεύω', russian: 'обожать' },
        { greek: 'τηλεφωνώ', russian: 'звонить' },
        { greek: 'κοστίζω', russian: 'стоить' },
        { greek: 'προτιμώ / προτιμάω', russian: 'предпочитать' },
        { greek: 'ανεβαίνω', russian: 'подниматься' },
        { greek: 'περπατώ / περπατάω', russian: 'ходить пешком' },
        { greek: 'κατεβαίνω', russian: 'спускаться, выходить из транспорта' },
        { greek: 'οδηγώ', russian: 'водить' },
        { greek: 'ζω', russian: 'жить' },
        { greek: 'συνδέω', russian: 'соединять' },
        { greek: 'μπορώ', russian: 'мочь' },
        { greek: 'εξηγώ', russian: 'объяснять' },
        { greek: 'επιστρέφω', russian: 'возвращаться' },
        { greek: 'ανάβω', russian: 'включать, зажигать' },
        { greek: 'σβήνω', russian: 'тушить, выключать' },
        { greek: 'αναχωρώ', russian: 'отправляться' }
    ]
});

window.LESSONS.push({
    lesson: 6.3,
    title: 'Прилагательные и наречия',
    words: [
        { greek: 'θερινός', russian: 'летний' },
        { greek: 'άνετος', russian: 'удобный' },
        { greek: 'οικολογικός', russian: 'экологический' },
        { greek: 'ιδανικός', russian: 'идеальный' },
        { greek: 'επόμενος', russian: 'следующий' },
        { greek: 'μειωμένος', russian: 'сниженный' },
        { greek: 'άλλος', russian: 'другой' },
        { greek: 'καταπληκτικός', russian: 'удивительный' },
        { greek: 'αργός', russian: 'медленный' },
        { greek: 'αγαπημένος', russian: 'любимый' },
        { greek: 'φανταστικός', russian: 'фантастический' },
        { greek: 'τέλειος', russian: 'идеальный, совершенный' },
        { greek: 'κανονικός', russian: 'нормальный' },
        { greek: 'κεντρικός', russian: 'центральный' },
        { greek: 'μαύρος', russian: 'чёрный' },
        { greek: 'απλός', russian: 'простой' },
        { greek: 'φτωχός', russian: 'бедный' },
        { greek: 'περίπου', russian: 'примерно' },
        { greek: 'όμως', russian: 'однако' },
        { greek: 'σίγουρα', russian: 'точно, конечно' },
        { greek: 'δεν πειράζει', russian: 'ничего страшного' },
        { greek: 'εντάξει', russian: 'хорошо' },
        { greek: 'άλλη φορά', russian: 'в другой раз' },
        { greek: 'λοιπόν', russian: 'итак' },
        { greek: 'ορίστε', russian: 'пожалуйста' },
        { greek: 'το ίδιο', russian: 'то же самое' },
        { greek: 'κάθε', russian: 'каждый' },
        { greek: 'μισό λεπτό', russian: 'минуточку' },
        { greek: 'κάθε πότε', russian: 'как часто' },
        { greek: 'πόσο συχνά', russian: 'как часто' },
        { greek: 'δίπλα', russian: 'рядом' },
        { greek: 'μακριά', russian: 'далеко' },
        { greek: 'πάλι', russian: 'опять' },
        { greek: 'το πρωί', russian: 'утром' },
        { greek: 'το μεσημέρι', russian: 'в обед' },
        { greek: 'το απόγευμα', russian: 'после обеда' },
        { greek: 'το βράδυ', russian: 'вечером' },
        { greek: 'τη νύχτα', russian: 'ночью' },
        { greek: 'τα μεσάνυχτα', russian: 'в полночь' }
    ]
});

window.LESSONS.push({
    lesson: 6.4,
    title: 'Приказы',
    words: [
        { greek: 'δώσε / δώστε', russian: 'дай / дайте' },
        { greek: 'πάρε / πάρτε', russian: 'возьми / возьмите' },
        { greek: 'βάλε / βάλτε', russian: 'положи, поставь / положите, поставьте' },
        { greek: 'βγάλε / βγάλτε', russian: 'достань, сними / достаньте, снимите' },
        { greek: 'φέρε / φέρτε', russian: 'принеси / принесите' },
        { greek: 'πες / πέστε', russian: 'скажи / скажите' },
        { greek: 'κοίταξε / κοιτάξτε', russian: 'посмотри / посмотрите' },
        { greek: 'άνοιξε / ανοίξτε', russian: 'открой / откройте' },
        { greek: 'κλείσε / κλείστε', russian: 'закрой / закройте' },
        { greek: 'δείξε / δείξτε', russian: 'покажи / покажите' },
        { greek: 'πήγαινε / πηγαίνετε', russian: 'иди / идите' },
        { greek: 'διάβασε / διαβάστε', russian: 'прочитай / прочитайте' },
        { greek: 'γράψε / γράψτε', russian: 'напиши / напишите' },
        { greek: 'κάνε / κάνετε', russian: 'сделай / сделайте' },
        { greek: 'περίμενε / περιμένετε', russian: 'подожди / подождите' },
        { greek: 'κατάλαβε / καταλάβετε', russian: 'пойми / поймите' },
        { greek: 'άναψε / ανάψτε', russian: 'включи, зажги / включите, зажгите' },
        { greek: 'σβήσε / σβήστε', russian: 'выключи, потуши / выключите, потушите' }
    ]
});

window.LESSONS.push({
    lesson: 998,
    title: 'Числа 1–1000',
    words: [
        // 1–10
        { greek: 'ένα', russian: 'один' },
        { greek: 'δύο', russian: 'два' },
        { greek: 'τρία', russian: 'три' },
        { greek: 'τέσσερα', russian: 'четыре' },
        { greek: 'πέντε', russian: 'пять' },
        { greek: 'έξι', russian: 'шесть' },
        { greek: 'επτά', russian: 'семь' },
        { greek: 'οκτώ', russian: 'восемь' },
        { greek: 'εννέα', russian: 'девять' },
        { greek: 'δέκα', russian: 'десять' },

        // 11–19
        { greek: 'έντεκα', russian: 'одиннадцать' },
        { greek: 'δώδεκα', russian: 'двенадцать' },
        { greek: 'δεκατρία', russian: 'тринадцать' },
        { greek: 'δεκατέσσερα', russian: 'четырнадцать' },
        { greek: 'δεκαπέντε', russian: 'пятнадцать' },
        { greek: 'δεκαέξι', russian: 'шестнадцать' },
        { greek: 'δεκαεπτά', russian: 'семнадцать' },
        { greek: 'δεκαοκτώ', russian: 'восемнадцать' },
        { greek: 'δεκαεννέα', russian: 'девятнадцать' },

        // десятки
        { greek: 'είκοσι', russian: 'двадцать' },
        { greek: 'τριάντα', russian: 'тридцать' },
        { greek: 'σαράντα', russian: 'сорок' },
        { greek: 'πενήντα', russian: 'пятьдесят' },
        { greek: 'εξήντα', russian: 'шестьдесят' },
        { greek: 'εβδομήντα', russian: 'семьдесят' },
        { greek: 'ογδόντα', russian: 'восемьдесят' },
        { greek: 'ενενήντα', russian: 'девяносто' },

        // сотни
        { greek: 'εκατό', russian: 'сто' },
        { greek: 'διακόσια', russian: 'двести' },
        { greek: 'τριακόσια', russian: 'триста' },
        { greek: 'τετρακόσια', russian: 'четыреста' },
        { greek: 'πεντακόσια', russian: 'пятьсот' },
        { greek: 'εξακόσια', russian: 'шестьсот' },
        { greek: 'επτακόσια', russian: 'семьсот' },
        { greek: 'οκτακόσια', russian: 'восемьсот' },
        { greek: 'εννιακόσια', russian: 'девятьсот' },

        // 1000
        { greek: 'χίλια', russian: 'тысяча' }
    ]
});

window.LESSONS.push({
    lesson: 999,
    title: 'Дополнительные слова',
    words: [
        { greek: 'σήμερα', russian: 'сегодня' },
        { greek: 'τίποτα', russian: 'ничего' },
        { greek: 'ο πεθερός', russian: 'тесть' },
        { greek: 'η πεθερά', russian: 'тёща' },
        { greek: 'η νοικοκυρά', russian: 'домохозяйка' },
        { greek: 'η/ο συνταξιούχος', russian: 'пенсионер' },
        { greek: 'πέθανε', russian: 'умер' },
        { greek: 'επίσης', russian: 'тоже' },
        { greek: 'ορίστε', russian: 'вот, пожалуйста' },
        { greek: 'για', russian: 'для' },
        { greek: 'ότι', russian: 'что' },
        { greek: 'όλα', russian: 'всё, все (вещи)' },
        { greek: 'πρώτη', russian: 'первый' },
        { greek: 'δείπνο', russian: 'ужин' },
        { greek: 'με τα πόδια', russian: 'пешком' },
        { greek: 'κουρασμένος', russian: 'уставший' },
        { greek: 'μπαρ/μπαράκι', russian: 'бар' },
        { greek: 'λογαριασμός', russian: 'счёт' },
        { greek: 'πληρώνω', russian: 'оплачивать' },
        { greek: 'έξω', russian: 'снаружи/внешний' },
        { greek: 'τυρόπιτα', russian: 'пирог с сыром' }
    ]
});