window.LESSONS = [
    {
        lesson: 1.0,
        title: 'Основные слова',
        words: [
            { greek: "το βιβλίο", russian: "книга" },
            { greek: "το τετράδιο", russian: "тетрадь" },
            { greek: "το περιοδικό", russian: "журнал" },
            { greek: "το μολύβι", russian: "карандаш" },
            { greek: "το στυλό", russian: "ручка" },
            { greek: "η πένα", russian: "ручка" },
            { greek: "το σχολείο", russian: "школа" },
            { greek: "το δωμάτιο", russian: "комната" },
            { greek: "το σπίτι", russian: "дом" },
            { greek: "το γραφείο", russian: "офис, кабинет, письменный стол" },
            { greek: "το τηλέφωνο", russian: "телефон" },
            { greek: "το ραδιόφωνο", russian: "радио" },
            { greek: "το ρολόι", russian: "часы" },
            { greek: "το αυτοκίνητο", russian: "машина" },
            { greek: "το παράθυρο", russian: "окно" },
            { greek: "η πόρτα", russian: "дверь" },
            { greek: "ο τοίχος", russian: "стена" },
            { greek: "το πάρκο", russian: "парк" },
            { greek: "το κουτί", russian: "коробка" },
            { greek: "το βάζο", russian: "ваза" },
            { greek: "το κομπιούτερ", russian: "компьютер" },
            { greek: "το ερμάρι", russian: "шкаф" },
            { greek: "το τραπέζι", russian: "стол" },
            { greek: "το πάτωμα", russian: "пол" },
            { greek: "το ταβάνι", russian: "потолок" },
            { greek: "το κλειδί", russian: "ключ" },
            { greek: "το διαμέρισμα", russian: "квартира" },
            { greek: "το λουλούδι", russian: "цветок" },
            { greek: "το καλάθι", russian: "корзина" },
            { greek: "το γράμμα", russian: "письмо" },
            { greek: "το κατάστημα", russian: "магазин" },
            { greek: "το πράγμα", russian: "вещь" },
            { greek: "το φόρεμα", russian: "платье" },
            { greek: "το μάθημα", russian: "урок" },
            { greek: "το μήλο", russian: "яблоко" },
            { greek: "το φρούτο", russian: "фрукт" },
            { greek: "το νερό", russian: "вода" },
            { greek: "το ψωμί", russian: "хлеб" },
            { greek: "ο μαθητής", russian: "ученик" },
            { greek: "η μαθήτρια", russian: "ученица" },
            { greek: "ο δάσκαλος", russian: "учитель" },
            { greek: "η δασκάλα", russian: "учительница" },
            { greek: "ο γιατρός", russian: "врач" },
            { greek: "ο κύριος", russian: "господин" },
            { greek: "η κυρία", russian: "госпожа" },
            { greek: "ο φοιτητής", russian: "студент" },
            { greek: "η φοιτήτρια", russian: "студентка" },
            { greek: "η καρέκλα", russian: "стул" },
            { greek: "το παιδί", russian: "ребёнок, дети" },
            { greek: "το ποδήλατο", russian: "велосипед" },
            { greek: "το πουκάμισο", russian: "рубашка" },
            { greek: "το παλτό", russian: "пальто" },
            { greek: "το σακάκι", russian: "куртка, пиджак" },
            { greek: "το καπέλο", russian: "шапка" },
            { greek: "το παντελόνι", russian: "брюки" },
            { greek: "ο πίνακας", russian: "доска, картина" },
            { greek: "ο χαρτοφύλακας", russian: "портфель" },
            { greek: "η τσάντα", russian: "сумка" },
            { greek: "η πόλη", russian: "город" },
            { greek: "το χωριό", russian: "деревня" },
            { greek: "το όνομα", russian: "имя" },
            { greek: "ο άντρας", russian: "мужчина, муж" },
            { greek: "η γυναίκα", russian: "женщина, жена" },
            { greek: "ο καθηγητής", russian: "преподаватель" },
            { greek: "η καθηγήτρια", russian: "преподавательница" },
            { greek: "η τάξη", russian: "класс" },
            { greek: "η χώρα", russian: "страна" }
        ]
    }
];

// Lesson 2: countries
window.LESSONS.push({
    lesson: 1.1,
    title: 'Страны',
    words: [
        { greek: 'η Ρωσία', russian: 'Россия' },
        { greek: 'η Ελλάδα', russian: 'Греция' },
        { greek: 'η Τουρκία', russian: 'Турция' },
        { greek: 'η Αγγλία', russian: 'Англия' },
        { greek: 'η Ισπανία', russian: 'Испания' },
        { greek: 'ο Καναδάς', russian: 'Канада' },
        { greek: 'ο Λίβανος', russian: 'Ливан' },
        { greek: 'η Βουλγαρία', russian: 'Болгария' },
        { greek: 'το Βέλγιο', russian: 'Бельгия' },
        { greek: 'η Γαλλία', russian: 'Франция' },
        { greek: 'η Γερμανία', russian: 'Германия' },
        { greek: 'η Κύπρος', russian: 'Кипр' },
        { greek: 'η Ιταλία', russian: 'Италия' },
        { greek: 'η Λευκορωσία', russian: 'Белоруссия' },
        { greek: 'η Ουκρανία', russian: 'Украина' }
    ]
});

// User-provided lesson (marked as "Урок 2" in user's list)
window.LESSONS.push({
    lesson: 2.0,
    title: 'Основные слова',
    words: [
        { greek: 'το επώνυμο', russian: 'фамилия' },
        { greek: 'το επίθετο', russian: 'фамилия' },
        { greek: 'η διεύθυνση', russian: 'адрес' },
        { greek: 'η περιοχή', russian: 'район' },
        { greek: 'ο ταχυδρομικός κώδικας', russian: 'почтовый индекс' },
        { greek: 'το σταθερό', russian: 'домашний телефон' },
        { greek: 'το κινητό', russian: 'мобильный' },
        { greek: 'ακριβώς', russian: 'именно, точно, ровно' },
        { greek: 'το νούμερο', russian: 'номер' },
        { greek: 'ο δρόμος', russian: 'дорога, улица, путь' },
        { greek: 'η θάλασσα', russian: 'море' },
        { greek: 'το φαρμακείο', russian: 'аптека' },
        { greek: 'ο ήλιος', russian: 'солнце' },
        { greek: 'ο ουρανός', russian: 'небо' },
        { greek: 'το μουσείο', russian: 'музей' },
        { greek: 'το εστιατόριο', russian: 'ресторан' },
        { greek: 'το περίπτερο', russian: 'киоск' },
        { greek: 'η ταβέρνα', russian: 'таверна' },
        { greek: 'το νοσοκομείο', russian: 'больница' },
        { greek: 'ο φούρνος', russian: 'хлебный магазин' },
        { greek: 'το μαγαζί', russian: 'магазин, заведение' },
        { greek: 'το θέατρο', russian: 'театр' },
        { greek: 'το ξενοδοχείο', russian: 'гостиница' },
        { greek: 'το πρόβλημα', russian: 'проблема' },
        { greek: 'το δημαρχείο', russian: 'мэрия' },
        { greek: 'το εργοστάσιο', russian: 'завод' },
        { greek: 'το ταχυδρομείο', russian: 'почта' },
        { greek: 'το βιβλιοπωλείο', russian: 'книжный магазин' },
        { greek: 'το αεροδρόμιο', russian: 'аэропорт' },
        { greek: 'το κρέας', russian: 'мясо' },
        { greek: 'το κρασί', russian: 'вино' },
        { greek: 'το γάλα', russian: 'молоко' },
        { greek: 'το ποτήρι', russian: 'стакан' },
        { greek: 'το μπουκάλι', russian: 'бутылка' },
        { greek: 'τα λεφτά', russian: 'деньги' },
        { greek: 'τα χρήματα', russian: 'деньги' },
        { greek: 'η θέρμανση', russian: 'отопление' },
        { greek: 'η εφημερίδα', russian: 'газета' },
        { greek: 'το ποδόσφαιρο', russian: 'футбол' },
        { greek: 'το ψάρι', russian: 'рыба' },
        { greek: 'η έκθεση', russian: 'выставка, сочинение' },
        { greek: 'το βράδυ', russian: 'вечер, вечером' },
        { greek: 'το παγωτό', russian: 'мороженое' },
        { greek: 'το πιάνο', russian: 'пианино' },
        { greek: 'ο χυμός', russian: 'сок' },
        { greek: 'ο καφές', russian: 'кофе' },
        { greek: 'το λιμάνι', russian: 'порт' },
        { greek: 'η στάση', russian: 'остановка' },
        { greek: 'η τράπεζα', russian: 'банк' },
        { greek: 'η πλατεία', russian: 'площадь' },
        { greek: 'ο κινηματογράφος', russian: 'кинотеатр, кинематограф' },
        { greek: 'το τρένο', russian: 'поезд' },
        { greek: 'το μετρό', russian: 'метро' },
        { greek: 'το λεωφορείο', russian: 'автобус' },
        { greek: 'ήδη / πια', russian: 'уже' },
        { greek: 'καλά', russian: 'хорошо' },
        { greek: 'το σκυλάκι', russian: 'собачка' },
        { greek: 'τώρα', russian: 'сейчас' },
        { greek: 'κοντά', russian: 'недалеко' },
        { greek: 'εδώ', russian: 'здесь' },
        { greek: 'εκεί', russian: 'там' },
        { greek: 'συχνά', russian: 'часто' },
        { greek: 'συνήθως', russian: 'обычно' },
        { greek: 'πάντα', russian: 'всегда' },
        { greek: 'σπάνια', russian: 'редко' },
        { greek: 'ποτέ', russian: 'никогда' },
        { greek: 'τα Ελληνικά', russian: 'греческий язык' },
        { greek: 'τα Ρωσικά', russian: 'русский язык' },
        { greek: 'τα Αγγλικά', russian: 'английский язык' },
        { greek: 'το πορτοφόλι', russian: 'кошелёк' },
        { greek: 'το παραμύθι', russian: 'сказка' }
    ]
});

// Lesson: Глаголы
window.LESSONS.push({
    lesson: 2.1,
    title: 'Глаголы',
    words: [
        { greek: 'μένω', russian: 'жить' },
        { greek: 'έχω', russian: 'иметь' },
        { greek: 'κάνω', russian: 'делать' },
        { greek: 'διαβάζω', russian: 'читать' },
        { greek: 'γράφω', russian: 'писать' },
        { greek: 'παίζω', russian: 'играть' },
        { greek: 'μαθαίνω', russian: 'учить' },
        { greek: 'μαγειρεύω', russian: 'готовить еду' },
        { greek: 'ξέρω', russian: 'знать' },
        { greek: 'βλέπω', russian: 'видеть' },
        { greek: 'κοιτάζω', russian: 'смотреть' },
        { greek: 'θέλω', russian: 'хотеть' },
        { greek: 'αγοράζω', russian: 'покупать' },
        { greek: 'δουλεύω', russian: 'работать' },
        { greek: 'καπνίζω', russian: 'курить' },
        { greek: 'καταλαβαίνω', russian: 'понимать' },
        { greek: 'σπουδάζω', russian: 'учиться (в ВУЗЕ)' },
        { greek: 'διδάσκω', russian: 'преподавать' },
        { greek: 'πηγαίνω', russian: 'идти, ходить, ехать, ездить' },
        { greek: 'περιμένω', russian: 'ждать' }
    ]
});

// Lesson 3: family & jobs
window.LESSONS.push({
    lesson: 3.0,
    title: 'Урок 3',
    words: [
        { greek: 'η οικογένεια', russian: 'семья' },
        { greek: 'η μητέρα', russian: 'мама' },
        { greek: 'η μαμά', russian: 'мама' },
        { greek: 'ο πατέρας', russian: 'папа' },
        { greek: 'ο μπαμπάς', russian: 'папа' },
        { greek: 'η κόρη', russian: 'дочь' },
        { greek: 'ο γιος', russian: 'сын' },
        { greek: 'ο αδελφός', russian: 'брат' },
        { greek: 'ο αδερφός', russian: 'брат' },
        { greek: 'η αδελφή', russian: 'сестра' },
        { greek: 'η αδερφή', russian: 'сестра' },
        { greek: 'τα αδέλφια', russian: 'братья и сёстры' },
        { greek: 'τα αδέρφια', russian: 'братья и сёстры' },
        { greek: 'ο παππούς', russian: 'дедушка' },
        { greek: 'η γιαγιά', russian: 'бабушка' },
        { greek: 'ο εγγονός', russian: 'внук' },
        { greek: 'η εγγονή', russian: 'внучка' },
        { greek: 'τα εγγόνια', russian: 'внуки' },
        { greek: 'ο θείος', russian: 'дядя' },
        { greek: 'η θεία', russian: 'тётя' },
        { greek: 'ο ξάδελφος', russian: 'двоюродный брат' },
        { greek: 'ο ξαδερφος', russian: 'двоюродный брат' },
        { greek: 'η ξαδέλφη', russian: 'двоюродная сестра' },
        { greek: 'η ξαδερφη', russian: 'двоюродная сестра' },
        { greek: 'τα ξαδέλφια', russian: 'двоюродные братья и сёстры' },
        { greek: 'τα ξαδέρφια', russian: 'двоюродные братья и сёстры' },
        { greek: 'ο ανιψιός', russian: 'племянник' },
        { greek: 'η ανιψιά', russian: 'племянница' },
        { greek: 'τα ανίψια', russian: 'племянники' },
        { greek: 'οι γονείς', russian: 'родители' },
        { greek: 'το σόι', russian: 'родня' },
        { greek: 'οι συγγενείς', russian: 'родственники' },
        { greek: 'το αγόρι', russian: 'мальчик' },
        { greek: 'το κορίτσι', russian: 'девочка' },
        { greek: 'η οικογενειακή κατάσταση', russian: 'семейное положение' },
        { greek: 'παντρεμένος', russian: 'женатый' },
        { greek: 'παντρεμένη', russian: 'замужняя' },
        { greek: 'ανύπαντρος', russian: 'неженатый' },
        { greek: 'ανύπαντρη', russian: 'незамужняя' },
        { greek: 'ελεύθερος', russian: 'свободный' },
        { greek: 'ελεύθερη', russian: 'свободная' },
        { greek: 'αρραβωνιασμένος', russian: 'обручённый' },
        { greek: 'αρραβωνιασμένη', russian: 'обручённая' },
        { greek: 'χωρισμένος', russian: 'разведённый' },
        { greek: 'χωρισμένη', russian: 'разведённая' },
        { greek: 'ο χήρος', russian: 'вдовец' },
        { greek: 'η χήρα', russian: 'вдова' },
        { greek: 'η δουλειά', russian: 'работа' },
        { greek: 'ο δικηγόρος', russian: 'адвокат' },
        { greek: 'η δικηγόρος', russian: 'адвокат' },
        { greek: 'ο ηλεκτρολόγος', russian: 'электрик' },
        { greek: 'η ηλεκτρολόγος', russian: 'электрик' },
        { greek: 'ο οδηγός', russian: 'водитель' },
        { greek: 'η οδηγός', russian: 'водитель' },
        { greek: 'ο μηχανικός', russian: 'инженер' },
        { greek: 'η μηχανικός', russian: 'инженер' },
        { greek: 'ο υπάλληλος', russian: 'служащий' },
        { greek: 'η υπάλληλος', russian: 'служащая' },
        { greek: 'ο ηθοποιός', russian: 'актёр' },
        { greek: 'η ηθοποιός', russian: 'актриса' },
        { greek: 'ο ταμίας', russian: 'кассир' },
        { greek: 'η ταμίας', russian: 'кассир' },
        { greek: 'ο αρχιτέκτονας', russian: 'архитектор' },
        { greek: 'η αρχιτέκτονας', russian: 'архитектор' },
        { greek: 'ο γραμματέας', russian: 'секретарь' },
        { greek: 'η γραμματέας', russian: 'секретарь' },
        { greek: 'ο δημοσιογράφος', russian: 'журналист' },
        { greek: 'η δημοσιογράφος', russian: 'журналистка' },
        { greek: 'ο φαρμακοποιός', russian: 'фармацевт' },
        { greek: 'η φαρμακοποιός', russian: 'фармацевт' },
        { greek: 'ο αρχαιολόγος', russian: 'археолог' },
        { greek: 'η αρχαιολόγος', russian: 'археолог' },
        { greek: 'ο φωτογράφος', russian: 'фотограф' },
        { greek: 'η φωτογράφος', russian: 'фотограф' },
        { greek: 'ο οδοντίατρος', russian: 'зубной врач' },
        { greek: 'η οδοντίατρος', russian: 'зубной врач' },
        { greek: 'ο μαθηματικός', russian: 'математик' },
        { greek: 'η μαθηματικός', russian: 'математик' },
        { greek: 'ο κομμωτής', russian: 'парикмахер' },
        { greek: 'η κομμώτρια', russian: 'парикмахерша' },
        { greek: 'ο εργάτης', russian: 'рабочий' },
        { greek: 'η εργάτρια', russian: 'рабочая' },
        { greek: 'ο πωλητής', russian: 'продавец' },
        { greek: 'η πωλήτρια', russian: 'продавщица' },
        { greek: 'ο αθλητής', russian: 'спортсмен' },
        { greek: 'η αθλήτρια', russian: 'спортсменка' },
        { greek: 'ο σερβιτόρος', russian: 'официант' },
        { greek: 'η σερβιτόρα', russian: 'официантка' },
        { greek: 'ο νοσοκόμος', russian: 'медбрат' },
        { greek: 'η νοσοκόμα', russian: 'медсестра' },
        { greek: 'ο άνεργος', russian: 'безработный' },
        { greek: 'η άνεργη', russian: 'безработная' },
        { greek: 'ο μάγειρας', russian: 'повар' },
        { greek: 'η μαγείρισσα', russian: 'повар' },
        { greek: 'ο τραγουδιστής', russian: 'певец' },
        { greek: 'η τραγουδίστρια', russian: 'певица' },
        { greek: 'ο φίλος', russian: 'друг' },
        { greek: 'η φίλη', russian: 'подруга' },
        { greek: 'μαζί', russian: 'вместе' },
        { greek: 'ταξιδεύω', russian: 'путешествовать' },
        { greek: 'το σούπερ μάρκετ', russian: 'супермаркет' },
        { greek: 'το κομμωτήριο', russian: 'парикмахерская' },
        { greek: 'το συνεργείο', russian: 'ремонтная мастерская, бригада' },
        { greek: 'ψάχνω (για)', russian: 'искать' },
        { greek: 'το ταμείο', russian: 'касса' },
        { greek: 'η ιστορία', russian: 'история' },
        { greek: 'το δικηγορικό γραφείο', russian: 'адвокатская контора' },
        { greek: 'το φωτογραφείο', russian: 'фотоателье' },
        { greek: 'η φωτογραφία', russian: 'фотография' }
    ]
});

window.LESSONS.push({
    lesson: 4.1,
    title: 'Существительные и прилагательные',
    words: [
        { greek: 'το καφενείο / η καφετέρια',      russian: 'кафе' },
        { greek: 'ο σταθμός',                      russian: 'станция, вокзал' },
        { greek: 'η αγγελία',                      russian: 'объявление' },
        { greek: 'η αμοιβή',                       russian: 'оплата услуг, гонорар' },
        { greek: 'ο χώρος',                        russian: 'место, пространство, территория, помещение' },
        { greek: 'η γραμματεία',                   russian: 'секретариат, приемная' },
        { greek: 'το ωράριο',                      russian: 'график работы, часы работы' },
        { greek: 'η ρεσεψιόν',                     russian: 'администрация, приемная' },
        { greek: 'η ώρα',                          russian: 'время, час' },
        { greek: 'η γνώση',                        russian: 'знание' },
        { greek: 'η εταιρεία',                     russian: 'компания, фирма' },
        { greek: 'το έντυπο',                      russian: 'бланк' },
        { greek: 'η εγγραφή',                      russian: 'запись, регистрация' },
        { greek: 'η εθνικότητα',                   russian: 'национальность' },
        { greek: 'η γλώσσα',                       russian: 'язык' },
        { greek: 'το επάγγελμα',                   russian: 'профессия' },
        { greek: 'η αρχαιολογία',                  russian: 'археология' },
        { greek: 'το πανεπιστήμιο',                russian: 'университет' },
        { greek: 'η κάρτα / ο χάρτης',             russian: 'карта' },
        { greek: 'το θρανίο',                      russian: 'парта' },
        { greek: 'το σφουγγάρι',                   russian: 'губка' },
        { greek: 'το ράφι',                        russian: 'полка' },
        { greek: 'η βιβλιοθήκη',                   russian: 'библиотека' },
        { greek: 'ο υπολογιστής',                  russian: 'компьютер' },
        { greek: 'το σπουδαστήριο',                russian: 'зал для занятий в учебном заведении' },
        { greek: 'ο μαρκαδόρος',                   russian: 'маркер' },
        { greek: 'το σακίδιο',                     russian: 'рюкзак' },
        { greek: 'το διάλειμμα',                   russian: 'перемена, перерыв' },
        { greek: 'το δίπλωμα / το πτυχίο',         russian: 'диплом' },
        { greek: 'το πρόγραμμα',                   russian: 'программа' },
        { greek: 'το αμφιθέατρο',                  russian: 'амфитеатр' },
        { greek: 'το κυλικείο',                    russian: 'буфет' },
        { greek: 'το μέρος',                       russian: 'место, часть' },
        { greek: 'ο μάγος',                        russian: 'маг' },
        { greek: 'τα νομικά',                      russian: 'правоведение, юриспруденция' },
        { greek: 'τα οικονομικά',                  russian: 'экономика' },
        { greek: 'η ψυχολογία',                    russian: 'психология' },
        { greek: 'η ιατρική',                      russian: 'медицина' },
        { greek: 'η φιλολογία',                    russian: 'филология' },
        { greek: 'η πληροφορική',                  russian: 'информатика' },
        { greek: 'η αρχιτεκτονική',                russian: 'архитектура' },
        { greek: 'τα παιδαγωγικά',                 russian: 'педагогика' },
        { greek: 'η μετάφραση / η διερμηνεία',     russian: 'перевод' },
        { greek: 'η σχολή',                        russian: 'факультет, школа' },
        { greek: 'το τμήμα',                       russian: 'отделение, отдел' },
        { greek: 'η αίθουσα',                      russian: 'зал' },
        { greek: 'το πάσο',                        russian: 'пропуск, проездной' },
        { greek: 'το εισιτήριο',                   russian: 'билет' },
        { greek: 'το μεταπτυχιακό',                russian: 'магистратура' },
        { greek: 'το διδακτορικό',                 russian: 'докторантура' },
        { greek: 'η εργασία',                      russian: 'работа, труд, письменная работа' },
        { greek: 'η μπίρα',                        russian: 'пиво' },
        { greek: 'το σουβλάκι',                    russian: 'шашлык' },
        { greek: 'το κεφάλι',                      russian: 'голова' },
        { greek: 'το καλοκαίρι',                   russian: 'лето, летом' },
        { greek: 'η μπλούζα',                      russian: 'блузка' },
        { greek: 'η αίτηση',                       russian: 'заявление, прошение' },
        { greek: 'η συμμετοχή',                    russian: 'участие' },
        { greek: 'οι σπουδές',                     russian: 'учёба' },
        { greek: 'οι προσωπικές πληροφορίες',      russian: 'личная информация' },
        { greek: 'τα κεφαλαία γράμματα',           russian: 'заглавные буквы' },
        { greek: 'το φύλο',                        russian: 'пол' },
        { greek: 'η ημερομηνία γέννησης',          russian: 'дата рождения' },
        { greek: 'το διαβατήριο (ο αριθμός διαβατηρίου)', russian: 'паспорт (номер паспорта)' },
        { greek: 'η ταυτότητα (ο αριθμός ταυτότητας)',    russian: 'удостоверение личности' },
        { greek: 'ο / η κτηνίατρος',               russian: 'ветеринар' },
        { greek: 'ο γυμναστής / η γυμνάστρια',     russian: 'инструктор в спортзале, учитель физкультуры' },
        { greek: 'ο ξυλουργός',                   russian: 'плотник' },
        { greek: 'ιδιωτικός',                      russian: 'частный' },
        { greek: 'ξένος',                          russian: 'иностранный' },
        { greek: 'φιλικός',                        russian: 'дружелюбный' },
        { greek: 'καλός',                          russian: 'хороший' },
        { greek: 'πλήρης',                         russian: 'полный' },
        { greek: 'πρωινός',                        russian: 'утренний' },
        { greek: 'λίγο',                           russian: 'немного' },
        { greek: 'καθόλου',                        russian: 'совсем (не)' },
        { greek: 'αρκετά',                         russian: 'достаточно' }
    ]
});

window.LESSONS.push({
    lesson: 4.1,
    title: 'Глаголы',
    words: [
        { greek: 'αγαπώ / αγαπάω',    russian: 'любить' },
        { greek: 'μιλώ / μιλάω',      russian: 'говорить' },
        { greek: 'ζητώ / ζητάω',      russian: 'просить, требовать, искать (человека)' },
        { greek: 'βοηθώ / βοηθάω',    russian: 'помогать' },
        { greek: 'μελετώ / μελετάω',  russian: 'изучать' },
        { greek: 'διψώ / διψάω',      russian: 'хотеть пить' },
        { greek: 'πεινώ / πεινάω',    russian: 'хотеть есть' },
        { greek: 'τραγουδώ / τραγουδάω', russian: 'петь' },
        { greek: 'πονώ / πονάω',      russian: 'чувствовать боль' },
        { greek: 'ρωτώ / ρωτάω',      russian: 'спрашивать' },
        { greek: 'απαντώ / απαντάω',  russian: 'отвечать' },
        { greek: 'σταματώ / σταματάω', russian: 'останавливаться' },
        { greek: 'φορώ / φοράω',      russian: 'носить' },
        { greek: 'φωνάζω',            russian: 'кричать, звать' },
        { greek: 'μένω',              russian: 'жить' },
        { greek: 'έχω',               russian: 'иметь' }
    ]
});


window.LESSONS.push({
    lesson: 999,
    title: 'Дополнительные слова',
    words: [
        { greek: 'σήμερα', russian: 'сегодня' },
        { greek: 'τίποτα', russian: 'ничего' },
        { greek: 'ο πεθερός', russian: 'тесть' },
        { greek: 'η πεθερά', russian: 'тёща' },
        { greek: 'η νοικοκυρά', russian: 'домохозяйка' },
        { greek: 'η/ο συνταξιούχος', russian: 'пенсионер' },
        { greek: 'πέθανε', russian: 'умер' },
        { greek: 'επίσης', russian: 'тоже' }
    ]
});